### ISSUE TITLE
getLocalizedURL() issues route with parameters..

### ISSUE THREAD

**Issue by alkzzz** [mcamara/laravel-localization#199]
Hello, i'm using this package to develop my multilingual site in Indonesia and English. It worked perfectly fine for routes without parameters. Such as for the route "/en/profil" (id) and route "/en/about" (en) user can switch language freely and get the exact route for the language they choose. 

But when I put slug in the route. For example: indonesian language route "/id/profil/tampil/{slug}". When the user change the language to English with getLocalizedUrl(), it should translated to "/en/about/show/{slug}". Instead it translated to "/en/profil/tampil/{slug}".

I already tried your example and still can't get it work. And yet when I manually check the route /en/about/show/{slug} is there. But the language chooser with getLocalizedURL() translate it differently ( /en/profil/tampil/{slug} ) so user will get 404 error.

**Comment by GregoryClaeyssens** [comment]
I'm having the same issue... URL parameters don't seem to work in all cases

```
/* this works */
Route::get(LaravelLocalization::transRoute('routes.jobs_index'), array('as' => 'jobs.index', 'uses' => 'JobController@index')); 
/* this works */
Route::get(LaravelLocalization::transRoute('routes.jobs_show'), array('as' => 'jobs.show', 'uses' => 'JobController@show')); 
/* this doesn't work */
Route::get(LaravelLocalization::transRoute('routes.solicit_show'), array('as' => 'jobs.solicit', 'uses' => 'JobController@solicit'));
/* this works */
Route::get(LaravelLocalization::transRoute('routes.news_index'), array('as' => 'news.index', 'uses' => 'NewsController@index')); 
/* this doesn't work */
Route::get(LaravelLocalization::transRoute('routes.news_show'),  array('as' => 'news.show', 'uses' => 'NewsController@show'));
```

nl/routes.php
```
'jobs_index'     => 'vacatures',
'jobs_show'     => 'vacatures/{jobofferingsID}',
'solicit_show'  => 'solliciteer/{jobofferingsID?}',
'news_index'     => 'nieuws',
'news_show'     => 'nieuws/{slug}',
```

fr/routes.php
```
'jobs_index'     => 'emplois',
'jobs_show'     => 'emplois/{jobofferingsID}',
'solicit_show'  => 'solicit/{jobofferingsID?}',
'news_index'     => 'nouvelles',
'news_show'   => 'nouvelles/{slug}',
```

I tried making the attribute mandatory by removing the question mark, that didn't 'fix' it. 
When you visit the solicit_show page, without that jobofferingsID it does work.



It all seems quite random to me, what works what doesn't... Maybe i'm just overseeing something obvious?
Checking for route translations seems to work fine, but when using the getLocalizedUrl() function it just changes /fr/ to /nl/ en leaves the url untranslated (as explained by @alkzzz)...

**Comment by juukie** [comment]
I'm having the same issues as mentioned above :(.

**Comment by GregoryClaeyssens** [comment]
Simple workaround that seems to work in my case...
```
<a rel="alternate" hreflang="{{$locale}}" href="{{  LaravelLocalization::getLocalizedURL( $locale, Request::url(), Route::current()->parameters()) }}">{{ $locale }}</a>
```

**Comment by MarcGuay** [comment]
I believe that this is the issue I've addressed here: https://github.com/mcamara/laravel-localization/pull/227

**Comment by GregoryClaeyssens** [comment]
@MarcGuay This didn't seem to help.

**Comment by tomzmtl** [comment]
I'm having the same issue right now.

*Route declaration*
`Route::get( Localize::transRoute('routes.products.sections') . '/{slug}', 'ProductsController@sections' );`

*Using this code to switch locales (only 2 locales)*
`Localize::getLocalizedURL( $altLocale )`

Will only translate the `/locale` bit of the URL and leave everything else untranslated.

**Comment by javidalpe** [comment]
Same here :(

**Comment by nickbr5** [comment]
Hi All,

I'm still experiencing the same problem as above. Is this one solved or not?

thx

**Comment by jasperjorna** [comment]
Is this related? https://github.com/mcamara/laravel-localization/pull/418

**Comment by kazak71** [comment]
I have the same problem, but I found a workaround.
See my post in https://github.com/mcamara/laravel-localization/issues/448

Good Luck
